### ISSUE TITLE
Can Rhino redefine the length property of Array Object?

### ISSUE THREAD

**Issue by yeguixin** [mozilla/rhino#572] opened 2019-06-13 02:59 UTC
#### Test case:

```
  var foo = function () {
          var arr = [];
          print(arr.length);
          Object.defineProperty(arr, "length", {
                  get: function(){
                          return 11;
                  }
          });
          print(arr.length);
  };
 
  foo();
```

#### Command:
> java -jar rhino-[version].jar -debug -version 200 testcase.js

> Outputs: 
> 0
> 11

This testcase shows that rhino can redefine get method (Line 4 - 8), while other JS engines such as SpiderMonkey, V8 cannot.

**Comment by rbri** [comment] 2019-07-20 11:36
Made a fix for this.

**Comment by p-bakker** [comment] 2021-06-29 11:54
Duplicate of #574

**Closed by p-bakker** 2021-06-29 11:54 UTC
