### ISSUE TITLE
linklistHasMap of Type conversion Bug

### ISSUE THREAD

**Issue by MikeGrateful** [mozilla/rhino#1280] opened 2022-11-11 05:20 UTC
public static NativeJavaMap j2js(Object e){
        NativeJavaMap jsob = (NativeJavaMap) Context.javaToJS( e, ScriptRuntime.getTopCallScope(Context.getCurrentContext()));
       return jsob;
    }

public static void debug(Object... e) {
.....//break point
}
In the debug method, e is the normal Js type
```
        //js
        os.debug(new Map());
```
In the debug method, e is still linkhasmap??
```
// x is java  LinkhasMap
let x = getdata();
os.debug(os.j2js(x));
```

**Comment by p-bakker** [comment] 2022-11-11 08:01
Hard to say what is going on here, because your code sample isn't a full, working/runnable sample, so no idea if you've spotted a bug or if whatever you're seeing is expected behavior.

If you want help, start with providing a runnable example demonstrating the issue

**Comment by p-bakker** [comment] 2022-11-11 13:36
You could fork https://replit.com/@PaulBakker1/Rhino-Embedded#Main.java and modify it to provide a working example if you please

**Comment by p-bakker** [comment] 2022-11-21 10:49
Closing for lack if input. Feel free to reopen with more information

**Closed by p-bakker** 2022-11-21 10:49 UTC
