### ISSUE TITLE
Json.stringify cannot display function types on each other!!!

### ISSUE THREAD

**Issue by MikeGrateful** [mozilla/rhino#1042] opened 2021-10-05 17:31 UTC
Json.stringify cannot display function types on each other

**Comment by tonygermano** [comment] 2021-10-05 17:33
Please show an example with the wrong and expected output. I have no idea what this means.

**Comment by MikeGrateful** [comment] 2021-10-05 17:41
public static Script cmpl(String script, String fileName) {
            return ScriptEngine.getInstance().evalSourceAndGetScript(script, fileName);
        }
    public Script evalSourceAndGetScript(String source, String file) {
        context = ContextFactory.getGlobal().enterContext();
        context.setOptimizationLevel(-1);
        context.setLanguageVersion(Context.VERSION_ES6);
        Script script = context.compileString(source, file, 1, null);
        return script;
    }
above is the interface Java provides to JS
function loadScriptToCmplObj(file) {
   
        let cmpl = os.vm.cmpl(src, file);
        gt.metaClassSource.push({file: file, cmpl: cmpl, src: ""});
    });

}
Json.stringify(  gt.metaClassSource  )

[{file:"x.js",src:""}]
cmpl cannot output

**Comment by MikeGrateful** [comment] 2021-10-05 17:47
cmpl is InterpretedFunction !! so  Json.stringify cannot output?

> Please show an example with the wrong and expected output. I have no idea what this means.

**Comment by MikeGrateful** [comment] 2021-10-05 18:01
![image](https://user-images.githubusercontent.com/15280143/136077879-eaf330a8-912d-4f74-94bb-1c56de5241d1.png)

**Comment by tonygermano** [comment] 2021-10-05 19:27
`typeof cmpl` evaluates to `function`, and per the spec, any Callable property stringifies to undefined, so `JSON.stringify()` is working correctly.

It's also described here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description

> `undefined`, `Functions`, and `Symbols` are not valid JSON values. If any such values are encountered during conversion they are either omitted (when found in an object) or changed to `null` (when found in an array).

You never said what you expected to see in the output.

**Comment by MikeGrateful** [comment] 2021-10-06 02:17
> `typeof cmpl` evaluates to `function`, and per the spec, any Callable property stringifies to undefined, so `JSON.stringify()` is working correctly.
> 
> It's also described here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description
> 
> > `undefined`, `Functions`, and `Symbols` are not valid JSON values. If any such values are encountered during conversion they are either omitted (when found in an object) or changed to `null` (when found in an array).
> 
> You never said what you expected to see in the output.

TQMH

so !     Is that the cue?  [{file:"x.js",cmpl:[function]src:""}]  ????
This is the eeng agile development

**Comment by tonygermano** [comment] 2021-10-06 05:47
Using `JSON.stringify()`, it is impossible to stringify a function by design. There is no way to represent a function in JSON. I do not understand what you want it to do.

**Comment by MikeGrateful** [comment] 2021-10-06 07:49
> Using `JSON.stringify()`, it is impossible to stringify a function by design. There is no way to represent a function in JSON. I do not understand what you want it to do.

I mean suggest built-in reminders..
If the argument is function, print a warning instead of nothing, okay

**Comment by MikeGrateful** [comment] 2021-10-06 07:49
I couldn't find a reason for this problem yesterday

> > Using `JSON.stringify()`, it is impossible to stringify a function by design. There is no way to represent a function in JSON. I do not understand what you want it to do.
> 
> I mean suggest built-in reminders.. If the argument is function, print a warning instead of nothing, okay

**Comment by p-bakker** [comment] 2021-10-06 08:27
> If the argument is function, print a warning instead of nothing, okay
If you want to suggest changes to how JavaScript works, please discuss your suggestions at https://esdiscuss.org/

Rhino adheres to the JavaScript (EcmaScript) standard

Closing this case as I think your question is answered

**Closed by p-bakker** 2021-10-06 08:27 UTC

**Comment by MikeGrateful** [comment] 2021-10-06 08:30
> > If the argument is function, print a warning instead of nothing, okay
> > If you want to suggest changes to how JavaScript works, please discuss your suggestions at https://esdiscuss.org/
> 
> Rhino adheres to the JavaScript (EcmaScript) standard
> 
> Closing this case as I think your question is answered



> Using `JSON.stringify()`, it is impossible to stringify a function by design. There is no way to represent a function in JSON. I do not understand what you want it to do.

tq
