### ISSUE TITLE
-strict does not seem to work

### ISSUE THREAD

**Issue by yeguixin** [mozilla/rhino#564] opened 2019-05-29 03:50 UTC
When executing the following script (named test.js) using command "rhino1.7.9-1.7.9.jar -strict test.js"

```
var a = function(){
    print(this);
}
a();
```
Outputs:
[object global]

This illustrates that  "-strict" dose not work.

**Comment by rbri** [comment] 2020-07-05 11:21
This is an duplicate of #442.

**Closed** 2024-07-15 10:37 UTC
Labels: Strict Mode
