### ISSUE TITLE
Considering Support Proxy?

### ISSUE THREAD

**Issue by xuchiya** [mozilla/rhino#1179] opened 2022-02-09 12:42 UTC
like : 
const p = new Proxy(target, handler)

**Comment by p-bakker** [comment] 2022-02-09 13:10
Duplicate of #268

**Closed by p-bakker** 2022-02-09 13:10 UTC

**Comment by p-bakker** [comment] 2023-07-10 08:11
> You can do something similar by implementing Scriptable.

Note that when implementing Scriptable.get in JavaScript as suggested, that is the get impl. returns (JavaScript) undefined, the 'proxy' returns null for the gotten property. If you need it to return undefined, the get method should return `org.mozilla.javascript.Undefined.SCRIPTABLE_UNDEFINED` instead
