### ISSUE TITLE
Rhino download page is outdated

### ISSUE THREAD

**Issue by veita** [mozilla/rhino#245] opened 2015-09-24 12:22 UTC
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Download_Rhino

**Comment by tntim96** [comment] 2015-09-24 22:42
This is a duplicate of #217

**Comment by gbrail** [comment] 2016-01-15 17:35
Fixed. Thanks for reminding us.

**Closed by gbrail** 2016-01-15 17:35 UTC
