### ISSUE TITLE
Class not found exception on ver. 1.7.14

### ISSUE THREAD

**Issue by Tango600** [mozilla/rhino#1190] opened 2022-03-03 11:18 UTC
```
        Context rhino = Context.enter();

        // Turn off optimization to make Rhino Android compatible
        rhino.setOptimizationLevel(-1);
        try {
            Scriptable scope = rhino.initStandardObjects(null);  <<<< Exception !!!

```

**Comment by tuchida** [comment] 2022-03-03 11:42
- #1156

Is the issue the same as this?

**Comment by Tango600** [comment] 2022-03-03 13:28
Possible may be. Looks like it.

**Comment by p-bakker** [comment] 2022-03-21 08:41
Duplicate of #1156

**Closed by p-bakker** 2022-03-21 08:41 UTC
Labels: Android
