### ISSUE TITLE
Undefined or not initialized variables with strange behavior

### ISSUE THREAD

**Issue by EduFrazao** [mozilla/rhino#1458] opened 2024-03-21 20:20 UTC
Hi. Undefined or not initialized variables presents a strange behavior in version 1.7.14

Like this code:
```javascript

var x = undefined;

if (!x) {
    // Never enters here
}
```

Not initialized variables also reports its types as strings

```javascript
var x;
print(typeof x)
```

This codes prints: "string"

Is this somehow expected?

Edit note:
With 1.7.13 works fine.

**Comment by zozo-yasuda** [comment] 2024-04-02 21:42
I tested in the current 1.7.15 snapshot, indeed:
```
var x = undefined;
if(x) print(x)  //yields nothing
if(!x) print(x) //prints "undefined"
```
I also checked `Boolean(undefined)`. This evaluates to false as it should, so maybe there's something wrong with the if logic. 
For the second issue, mine printed `undefined` so this was probably fixed.


I'll add these as test cases when I familiarize myself more with the repo.

**Comment by EduFrazao** [comment] 2024-04-03 00:23
> I tested in the current 1.7.15 snapshot, indeed:
> 
> ```
> var x = undefined;
> if(x) print(x)  //yields nothing
> if(!x) print(x) //prints "undefined"
> ```
> 
> I also checked `Boolean(undefined)`. This evaluates to false as it should, so maybe there's something wrong with the if logic. For the second issue, mine printed `undefined` so this was probably fixed.
> 
> I'll add these as test cases when I familiarize myself more with the repo.

Hi. Thanks for testing.
Did you test the output of "typeof x" after set it as undefined?

**Comment by p-bakker** [comment] 2024-06-22 10:17
@EduFrazao Rhino 1.7.15 had been released. 

Could you validate if the issue you had in 1.7.14 is still present our not?

**Comment by p-bakker** [comment] 2024-06-22 11:15
If this issue is still present in 1.7.15, it would be great if you could try it before and after the merging of https://github.com/mozilla/rhino/pull/979, which is a merged PR that made changes in the area of undefined handling

**Comment by p-bakker** [comment] 2024-08-15 17:50
@gbrail any chance this regression might be due to the changes you made in #979?

**Comment by p-bakker** [comment] 2024-08-21 16:47
@gbrail quick ping in case this fell off the bottom of the list 🙂

**Comment by gbrail** [comment] 2024-08-21 16:52
I tried this on the master branch and I didn't see the original behavior
described, so I'd want to understand what exactly the original poster did
to get this result.

**Comment by p-bakker** [comment] 2024-08-21 19:45
My bad, I misread the second comment in that I thought it confirmed the bug, but it did the opposite

@EduFrazao please provide more details on how to reproduce or at least how you interact with Rhino/execute your JS code, because we cannot reproduce the behaviour your reporting, neither in master not with the 1.7.14 release

Without a way to reproduce the issue, there's not much we can do with this case

**Comment by p-bakker** [comment] 2024-09-06 18:35
Am closing this for lack of actionable input. Feel free to reopen with a reproducible example

**Closed by p-bakker** 2024-09-06 18:35 UTC
Labels: bug, Regression
