### ISSUE TITLE
ES5 Object not accessible when used in commonjs module

### ISSUE THREAD

**Issue by dsolimando** [mozilla/rhino#95] opened 2012-11-05 19:48 UTC
This code:

Object.defineProperties(obj, {
    "property1": { value: true,  writable: true },
    "property2": { value: "Hello", writable: false}
});

will fail with the following exception:

org.mozilla.javascript.EcmaError: ReferenceError: "Object" is not defined.

**Comment by szegedi** [comment] 2023-02-08 19:13
Works for me:
```java
import java.io.StringReader;
import java.net.URI;
import java.net.URISyntaxException;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.commonjs.module.Require;
import org.mozilla.javascript.commonjs.module.RequireBuilder;
import org.mozilla.javascript.commonjs.module.provider.ModuleSource;
import org.mozilla.javascript.commonjs.module.provider.ModuleSourceProvider;
import org.mozilla.javascript.commonjs.module.provider.StrongCachingModuleScriptProvider;

public class Main2 {
    public static void main(String[] args) {
        try(Context cx = Context.enter()) {
            cx.setOptimizationLevel(-1);
            Scriptable scope = cx.initStandardObjects();
            Require r = new RequireBuilder()
                .setModuleScriptProvider(new StrongCachingModuleScriptProvider(
                    new ModuleSourceProvider() {
                        @Override public ModuleSource loadSource(String moduleId, Scriptable paths,
                            Object validator) throws URISyntaxException {
                            var base = new URI("http://localhost/");
                            return loadSource(base.resolve(moduleId), base, validator);
                        }

                        @Override
                        public ModuleSource loadSource(URI uri, URI baseUri, Object validator) {
                            return new ModuleSource(
                                new StringReader(
                                    "var obj={}; Object.defineProperties(obj, {\n"
                                     + "\"property1\": { value: true, writable: true },\n"
                                     + "\"property2\": { value: \"Hello\", writable: false}\n"
                                     + "});"), null, uri, baseUri, validator);
                        }
                    })
                )
                .createRequire(cx, scope);
            r.install(scope);
            cx.evaluateString(scope, "require('whatever.js')", "", 1, null);
        }
    }
}
```
This programs exits without errors. Try to introduce a typo in "definePropertes" and you'll see it fails (so it does work without the typo.)

**Comment by p-bakker** [comment] 2023-02-08 20:35
Closing as cannot be reproduced. Feel free to reopen with a reproducible example

**Closed by p-bakker** 2023-02-08 20:35 UTC
Labels: CommonJS, Triage
