### ISSUE TITLE
Consts defined in loop blocks retain their values between iterations and after the loop

### ISSUE THREAD

**Issue by michbarsinai** [mozilla/rhino#1310] opened 2023-03-06 22:23 UTC
Given the following code, Rhino and Deno print different outputs. (the `out` function is just a compatibility layer between the two engines):

```javascript
function out(x){
    if ( typeof print != "undefined" ) {
        print(x);
    } else {
        console.log(x);
    }
}

let loopCount=3;
while ( loopCount-- ) {
   const i=loopCount;
   out(i);
}

// out(i);
```

Rhino prints:
```
$ java -jar rhino-1.7.14.jar  /Users/michael/sandbox/sm1/spec/js-dis/const.js
2
2
2
```

While Deno prints:
```
$ deno run /Users/michael/sandbox/sm1/spec/js-dis/const.js
2
1
0
```

Might be useful to note that when the last line is un-commented, Deno complains that `i` is not defined at that line, whereas Rhino prints `2`. However, if `i` is defined as `let`, Rhino behaves like Deno, and complains that `i` is not defined.

Seems like Rhino defines `const`s on a parent scope of the correct scope (maybe where `var`s would have been defined?), but I'm no expert in Rhino's internals.

**Comment by p-bakker** [comment] 2023-03-07 07:21
Duplicate of #939

**Closed by p-bakker** 2023-03-07 07:21 UTC
