### ISSUE TITLE
String comparing problem

### ISSUE THREAD

**Issue by SavchenkoVV** [mozilla/rhino#1283] opened 2022-11-21 12:57 UTC
'name' === 'name'                                          // true
String('name') === String('name')                // false  

Why wrapped strings not equals ? 
And how it possible to use switch operator with java string?

**Comment by p-bakker** [comment] 2022-11-21 13:06
Most likely due to how you've configured Rhino, see https://github.com/mozilla/rhino/issues/247#issuecomment-876770452

**Comment by SavchenkoVV** [comment] 2022-11-21 13:19
> Most likely due to how you've configured Rhino

Thanks for replying.
Tried with the setJavaPrimitiveWrap setting (true/false) - no changes in my case.

**Comment by p-bakker** [comment] 2022-11-21 13:32
How are you getting your Java String instances then?

**Comment by SavchenkoVV** [comment] 2022-11-22 06:41
By call lambda, but it is not important. Problem in comparing wrapped strings 

String('name') === String('name') // false

**Comment by p-bakker** [comment] 2022-11-22 07:50
> By call lambda, but it is not important

Well, depending on the  setJavaPrimitiveWrap setting they ought to be wrapped as Native JavaScript strings or not. When they are JavaScript strings, String('name') === String('name') should yield true, but if they are Java String instances it's imho expected that String('name') === String('name') yields false, as it would in Java because you're comparing instances.

**Comment by SavchenkoVV** [comment] 2022-11-22 08:28
I tested setJavaPrimitiveWrap with true and false.
Always  String('name') === String('name')  // false
Maybe i do something wrong...

As i understand switch operator use === to compare in cases.
So, if yot have string param v and do 
```
switch(String(v).toLowerCase()) {
}
```
no one case will work.
May be it releted with #891

**Comment by p-bakker** [comment] 2022-11-22 17:16
Without having some sample code that reproduces the issue, there's no telling whether this is expected behavior, a bug or whether you're doing something wrong

**Comment by p-bakker** [comment] 2023-10-17 14:00
Tried `new java.lang.String('name').length() && new java.lang.String('name') !== new java.lang.String('name') && String(new java.lang.String('name')) === String(new java.lang.String('name'))` but yields true as expected. 

This code shows that:
1. a JavaString is not wrapped (as it has a .length() method (Java), instead of .length property (JavaScript) 
2. comparing to Java String instances returns false
3. comparing to Java String instances wrapped in a JavaScript string returns true

So afaics all works as expected. As no sample code has been provided that reproduces the issue, I'm closing this issue

Feel free to reopen with a testcode reproducing the issue

**Closed by p-bakker** 2023-10-17 14:00 UTC
