### ISSUE TITLE
Question on the prototype used in BaseFunction.hasInstance(Scriptable instance)

### ISSUE THREAD

**Issue by RuralHunter** [mozilla/rhino#1482] opened 2024-06-06 06:34 UTC
Look the code of [this line](https://github.com/mozilla/rhino/blob/c6a873f61fe7d32a560feca9d66318e2586ef169/src/org/mozilla/javascript/BaseFunction.java#L96), it uses the [[Prototype]] of the function object as the prototype to check. According to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof), should we use the prototype property instead? That is, maybe change the code like this:
`Object protoProp = hasPrototypeProperty() ? getPrototypeProperty() : ScriptableObject.getProperty(this, "prototype");`

**Comment by rbri** [comment] 2024-06-06 06:58
hmmmm...


ScriptableObject.getProperty(this, "prototype"); already calls getPrototypeProperty() for BaseFunction.
![image](https://github.com/mozilla/rhino/assets/2544132/d6209987-5862-42ab-9a9f-48fd5a4135e6)

Do you have some test code that shows a problem here?
Did a quick test with 
![image](https://github.com/mozilla/rhino/assets/2544132/72180633-829b-47be-95dd-92038f77980d)
but works fine...

**Comment by RuralHunter** [comment] 2024-06-06 07:14
I have a function object throws exception of "msg.instanceof.bad.prototype" in hasInstance() check. The problem is the function has a 'prototype' slot set to undefined somehow. IdScriptableObject returns 'undefined' as the prototype [here](https://github.com/mozilla/rhino/blob/c6a873f61fe7d32a560feca9d66318e2586ef169/src/org/mozilla/javascript/IdScriptableObject.java#L369). I haven't figured out how the function is created yet since it's in a large obfuscated script.

**Comment by rbri** [comment] 2024-06-06 08:00
> have a function object
do you know the class of that object?

**Comment by RuralHunter** [comment] 2024-06-06 08:30
yeah I meant the function/class itself. It's defined like this:
```
(u = function e() {
                                    var r = e._v;
                                    return (0,
                                    e._u)(r[0], arguments, r[1], r[2], this)
                                }
                                )._v = [s, o, g];
```
But I haven't found out where the 'prototype' is set to undefined yet.

**Comment by RuralHunter** [comment] 2024-06-06 08:34
oh it's a InterpretedFunction if you mean that.

**Comment by RuralHunter** [comment] 2024-06-11 06:51
ok, I figured out the test case:
```
"use strict";
var f = function () {};
var a1="proto";
var p=a1+'type'; //this constructs a ConsString in rhino
print('before: '+f.prototype);
Object.defineProperty(f,p,{});
print('after: '+f.prototype);//undefined
var p=new f();
print(p instanceof f);//fails here
```
The key point is [here](https://github.com/mozilla/rhino/blob/c6a873f61fe7d32a560feca9d66318e2586ef169/src/org/mozilla/javascript/IdScriptableObject.java#L857). The key parameter generated in above code a ConsString object, not a String. If the key parameter is a String object like this:
`Object.defineProperty(f,'prototype',{});`
The code runs fine.

**Comment by rbri** [comment] 2024-06-11 07:10
@RuralHunter great, wiff have a look at the end of the week. Thanks for all the hard work on figuring this out...

**Comment by rbri** [comment] 2024-06-13 06:36
@RuralHunter do you need that for rhino or is core-js ok as starting point.
Because of the huge refactoring it might take a bit longer to do it the rhino way...

**Comment by RuralHunter** [comment] 2024-06-13 06:43
core-js is just fine for me.

**Comment by rbri** [comment] 2024-06-13 17:58
@RuralHunter please try 4.3.0-SNAPSHOT

**Comment by gbrail** [comment] 2024-06-13 18:06
I haven't followed the whole thing, but changing IdScriptableObject to
instead check "instanceof CharSequence" would be a pretty small fix to try.

**Comment by rbri** [comment] 2024-06-13 18:14
Yes, thats the plan and it works already here. PR is on the way...

Am 13. Juni 2024 20:07:16 MESZ schrieb Greg Brail ***@***.***>:
>I haven't followed the whole thing, but changing IdScriptableObject to
>instead check "instanceof CharSequence" would be a pretty small fix to try.
>

**Comment by RuralHunter** [comment] 2024-06-14 02:28
Thanks, the fix works.

**Comment by rbri** [comment] 2024-06-15 06:44
fixed with #1489 

Thanks a lot @RuralHunter for finding the root cause - i know how painful and time consuming this usually is (even harder if you have this obfuscated code)

**Closed by rbri** 2024-06-15 06:44 UTC

**Comment by RuralHunter** [comment] 2024-06-17 02:31
It's my pleasure to make a little contribute to the projects. Thanks for the quick fix as always.
