### ISSUE TITLE
Detection of redefined constants ignores block scope

### ISSUE THREAD

**Issue by sbabcoc** [mozilla/rhino#1480] opened 2024-05-27 17:49 UTC
Opening the Selenium project web site (https://selenium.dev) with **HtmlUnitDriver**, I get the following error message:
```
TypeError: redeclaration of const n. (https://www.selenium.dev/js/main.min.0a56205ed1c75268f017591e5418fdb944578a279fe7c7abe3981ebed191c341.js#5)
```
The code is minified, which makes it difficult to read and obscures the specific declaration that's triggering the error, but it appears that the error report is incorrect. Although there are 52 declarations of `const n`, each of them appears to be defined in a distinct block scope.

**Comment by p-bakker** [comment] 2024-06-01 19:28
Duplicate of #939

**Closed** 2024-06-22 08:55 UTC
Labels: Ecma Incompatibility
