### ISSUE TITLE
Rhino link in the "About" section is broken

### ISSUE THREAD

**Issue by akkadaya** [mozilla/rhino#1452] opened 2024-02-28 10:04 UTC
Rhino link in the "About" section is broken, use https://mozilla.github.io/rhino/ instead.

<img width="330" alt="image" src="https://github.com/mozilla/rhino/assets/1834445/77078aac-bcc6-4425-ad7c-bc84da98300a">

**Comment by michaelachrisco** [comment] 2024-03-05 19:21
It might need to be this: http://mozilla.github.io/rhino/

**Comment by p-bakker** [comment] 2024-05-21 07:22
Duplicate of #954

**Closed** 2024-05-21 07:23 UTC
