### ISSUE TITLE
rhino doesn't support js class

### ISSUE THREAD

**Issue by LightSun** [mozilla/rhino#524] opened 2019-02-18 08:55 UTC
for test , I have found that rhino doesn't support js class ? 
even if the class is simple.
```java
class Student{ 
}
```

exception is :
org.mozilla.javascript.EvaluatorException: missing ; before statement (/untitled0.js#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
	at org.mozilla.javascript.Parser.addError(Parser.java:260)
	at org.mozilla.javascript.Parser.reportError(Parser.java:328)
	at org.mozilla.javascript.Parser.reportError(Parser.java:315)
	at org.mozilla.javascript.Parser.reportError(Parser.java:308)
	at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1275)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1252)
	at org.mozilla.javascript.Parser.statement(Parser.java:1109)
	at org.mozilla.javascript.Parser.parse(Parser.java:648)
	at org.mozilla.javascript.Parser.parse(Parser.java:607)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2532)
	at org.mozilla.javascript.Context.compileReader(Context.java:1476)
	at org.mozilla.javascript.Context.compileReader(Context.java:1448)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1290)
	at heaven7.TestJs.loadJs(TestJs.java:85)
	at heaven7.TestJs.main(TestJs.java:22)

**Comment by gbrail** [comment] 2019-02-20 08:33
You are correct -- Rhino does not have support for the "class" syntax. I
have not heard anyone talk about how they are working on this. However,
there are a number of people working on the project with various levels of
skills and perhaps someone could contribute this feature.

**Comment by LightSun** [comment] 2019-02-20 12:19
I think you should use the DSL framework to parse the syntax, such as antlr.  so that parse js could be easier.

**Comment by p-bakker** [comment] 2021-06-29 06:59
Duplicate of #835

**Closed by p-bakker** 2021-06-29 06:59 UTC
