### ISSUE TITLE
menory leak on android kitkat with big files

### ISSUE THREAD

**Issue by krudos** [mozilla/rhino#278] opened 2016-05-21 19:31 UTC
when i load a big js file, around 500kb it give me a  java.lang.StackOverflowError but only on android kitkat? does anyone have problem like this?

**Comment by nickdeis** [comment] 2016-09-02 22:06
Not 100% sure this may be your issue:
At around 400kb+, Rhino will will hit some sort of stackoverflow or method length limitation. This is due to the limitations of the Java Specification on methods lengths and the limitation of certain java compilers.
Your issue sounds like the latter.
The solution here is not to compile your javascript, but instead evaluate it. This comes with performance costs.

Best,
Nick

**Comment by p-bakker** [comment] 2021-07-05 19:09
Duplicate of #286

**Closed by p-bakker** 2021-07-05 19:09 UTC
Labels: Android
