### ISSUE TITLE
java.lang.VerifyError in language/statements/try of test262

### ISSUE THREAD

**Issue by tuchida** [mozilla/rhino#915] opened 2021-05-29 09:50 UTC
When I enable language/statements/try in test262, I get the following error.

```
org.mozilla.javascript.tests.Test262SuiteTest > test262Case[js=language/statements/try/S12.14_A7_T1.js, opt=0, strict=false] FAILED
    java.lang.VerifyError at Test262SuiteTest.java:217

...

org.mozilla.javascript.tests.Test262SuiteTest > test262Case[js=language/statements/try/S12.14_A7_T3.js, opt=0, strict=false] FAILED
    java.lang.VerifyError at Test262SuiteTest.java:217
```
With JavaScript code like this
```js
try{
  try{
    throw "ex1";
  }finally{
    try{
      throw "ex2";
    }catch(er1){
    }
  }
}catch(er2){
}
```
I got an error like the following
```
Exception in thread "main" java.lang.VerifyError: Stack map does not match the one at exception handler 91
Exception Details:
  Location:
    org/mozilla/javascript/gen/_stdin__1._c_script_0(Lorg/mozilla/javascript/gen/_stdin__1;Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;Lorg/mozilla/javascript/Scriptable;[Ljava/lang/Object;)Ljava/lang/Object; @91: nop
  Reason:
    Type top (current frame, locals[5]) is not assignable to 'java/lang/Object' (stack map, locals[5])
  Current Frame:
    bci: @52
    flags: { }
    locals: { 'org/mozilla/javascript/gen/_stdin__1', 'org/mozilla/javascript/Context', 'org/mozilla/javascript/Scriptable', 'org/mozilla/javascript/Scriptable', '[Ljava/lang/Object;' }
    stack: { 'org/mozilla/javascript/JavaScriptException' }
  Stackmap Frame:
    bci: @91
    flags: { }
    locals: { 'org/mozilla/javascript/gen/_stdin__1', 'org/mozilla/javascript/Context', 'org/mozilla/javascript/Scriptable', 'org/mozilla/javascript/Scriptable', '[Ljava/lang/Object;', 'java/lang/Object', top, 'org/mozilla/javascript/Scriptable' }
    stack: { 'java/lang/Throwable' }
```
https://app.circleci.com/pipelines/github/mozilla/rhino/394/workflows/06f40ab3-873d-4ffd-b26f-753722081c8a/jobs/400/tests

I investigated the cause of this, but could not find it. If there is any way to find out, please let me know. For example, is there any way to isolate whether the StackMapTable is wrong or the bytecode itself is wrong?

**Comment by tuchida** [comment] 2021-05-29 09:53
This is an excerpt of a dump of a class file output by `ClassFileWriter` and analyzed by `javap`.
It seems that inefficient bytecodes are being output due to the large number of `nop`.
```
        33: athrow
        34: nop
        35: nop
        36: nop
        37: nop
        38: nop
        39: nop
        40: nop
        41: nop
        42: nop
        43: nop
        44: nop
        45: nop
        46: nop
        47: nop
        48: nop
        49: nop
        50: nop
        51: athrow
        52: nop
        53: nop
        54: athrow
        55: nop
        56: nop
        57: nop
        58: nop
        59: nop
        60: nop
        61: nop
        62: nop
        63: nop
        64: nop
        65: nop
        66: nop
        67: nop
        68: nop
        69: nop
        70: nop
        71: nop
        72: nop
        73: nop
        74: nop
        75: nop
        76: nop
        77: nop
        78: nop
        79: nop
        80: nop
        81: nop
        82: athrow
        83: nop
        84: nop
        85: nop
        86: nop
        87: athrow
        88: nop
        89: nop
        90: athrow
        91: nop
        92: nop
        93: nop
        94: nop
        95: nop
        96: nop
        97: nop
        98: athrow
        99: nop
       100: nop
```

**Comment by p-bakker** [comment] 2021-06-29 09:53
No expert here, but:
- https://github.com/mozilla/rhino/issues/407 might be a potential duplicate of this case
- maybe an idea to take the compiled bytecode and (try to) decompile it back to Java? A similar approach was taken in https://github.com/mozilla/rhino/issues/376#issuecomment-356059375

**Comment by tuchida** [comment] 2021-06-29 10:17
Thanks!
This is the output of `javap`. There are a lot of `nop` in `_c_script_0`, which looks inefficient.
https://gist.github.com/tuchida/7dda6b1ea8476e24c4fddc7b8e3229b1

**Comment by p-bakker** [comment] 2021-06-29 12:24
What if you take that try.class file and try to decompile it, for example using http://www.javadecompilers.com/?

Maybe if it decompiles, some sense can be made of the resulting Java code

**Comment by tuchida** [comment] 2021-06-29 12:40
> http://www.javadecompilers.com/

I tried all the decompilers, but none of them output the correct `_c_script_0`.
Perhaps the class file itself is corrupted.

**Comment by p-bakker** [comment] 2021-06-29 12:45
As I said, no expert here on bytecode stuff, but that would be my guess as well, that the class is corrupt due to bad bytecode generation.

One thing to try is to create a try2.class from a similar snippet of JavaScript, but one that doesn't display this VerifyError and see if that one does decompile. If that is the case, I think its fairly safe to say that the bytecode generation for JS snippet above is wrong.

**Comment by gbrail** [comment] 2021-06-29 16:11
"git bisect" tells me unhelpfully that this bug started happening when we
switched the target of the bytecode generation from 1.6 to 1.8, which
happened in 2017 with commit f3fff473ed6489aa86eace270a90443ed1572265.
(Literally all it does is change the version of the generated bytecode.)
That would result in a change in the header that's in the generated
bytecode that specifies the version and that would be it. I imagine maybe
the JVM tightened up the verification rules at that point. Unfortunately
that doesn't really help.

**Comment by p-bakker** [comment] 2021-06-29 17:12
No idea if at all related, but found the following in https://www.oracle.com/java/technologies/javase/8-compatibility-guide.html:
> Verification of the invokespecial instruction has been tightened when the instruction refers to an instance initialization method ("<init>").

And in https://www.oracle.com/java/technologies/compatibility.html there's talk about stackmaps and verification

Hope this helps

**Comment by gbrail** [comment] 2021-06-29 17:22
I think it's just that before Java 7, stack maps weren't required, and
after that they were. I think that Rhino may have always been generating an
invalid stack map for this case. It's going to take some thinking to figure
it out though.

**Comment by carlosame** [comment] 2021-10-18 17:20
Maybe it's that `ClassFileWriter.finalizeSuperBlockStarts()` is not being called when it needs to be, or is not doing something that it should. Finding a short reproducer (short enough to hardcode it in `ClassFileWriterTest`) may not be easy.

As if this stuff wasn't already a mess, turns out that the `ClassFileWriterTest` class belongs to the `org.mozilla.javascript.classfile.tests` package but is in the `testsrc/org/mozilla/classfile/tests` directory. Cannot run `ClassFileWriterTest` from Eclipse due to that, I wonder if there is a reason why the file is at the wrong directory (or has the wrong package name). If there is a real reason, a comment there would help.

**Comment by tuchida** [comment] 2021-10-22 00:24
@carlosame `ClassFileWriterTest` was added by me in #831.
I'm using `./gradlew test`, but if you have problems with Eclipse, you are welcome to fix it.

**Closed** 2021-11-18 21:58 UTC
Labels: bug, compilation
