### ISSUE TITLE
An issue about Object.prototype.isPrototypeOf

### ISSUE THREAD

**Issue by YiWen-y** [mozilla/rhino#656] opened 2020-04-04 14:12 UTC
###### Revision
rhino-1.7.11

###### Test case
```
var f = function (){
    print(typeof Object.prototype.isPrototypeOf);
    var a = Object.prototype.isPrototypeOf.call(undefined, []);
    print("a:", a);
};
f();
```

###### Execution steps
    java -jar rhino-1.7.11.jar -debug -version 200 testcase.js

###### Output
 ```
function
a: false
```
###### Expected behavior
Throw a Type Error in line 3.

###### Description
According to ES standard, the `this` value should be converted via `ToObject` in case of the `isPrototypeOf` call . The `ToObject` should throw and error for `undefined` values.

**Comment by rbri** [comment] 2020-05-19 06:44
Have added a pull request but i can't reproduce your finding. What is wrong with the test?

**Comment by rbri** [comment] 2020-05-20 05:14
This is fixed now. Please close.

**Closed** 2020-05-25 08:16 UTC
