### ISSUE TITLE
ARROW_FUNCTION position set error

### ISSUE THREAD

**Issue by nabice** [mozilla/rhino#303] opened 2017-04-24 09:21 UTC
JS Code:
`setTimeout(() => {}, 0);`

In org.mozilla.javascript.Parser.java, line 887,
params.position is -1, this will make a wrong FunctionNode position.

**Comment by hyb1996** [comment] 2017-05-15 03:38
Rhino supports arrow function? I try your code but only get a syntax error.

**Comment by nabice** [comment] 2017-05-15 03:54
支持的。可能你没有用到最新的版本？

**Comment by hyb1996** [comment] 2017-05-15 04:22
I am using the latest release [1.7.7.1](https://github.com/mozilla/rhino/releases/tag/Rhino1_7_7_1_RELEASE) but cannot run any code with arrow function. How to enable this feature? 
怎么支持呀 我设置语言版本为1.8和ES6也不行耶

**Comment by nabice** [comment] 2017-05-15 04:38
不太清楚你怎么弄的，直接编译最新的是可以的。没有进行什么设置。

**Comment by hyb1996** [comment] 2017-05-15 07:08
I finally found it was supported in the latest [SNAPSHOT](http://oss.jfrog.org/repo/org/mozilla/rhino/1.7.8-SNAPSHOT/).

**Comment by Yidadaa** [comment] 2017-07-02 04:38
@hyb1996 活捉autoJS作者2333

**Comment by gbrail** [comment] 2017-08-15 19:58
Since this seems to be fixed in master I'm closing this.

**Comment by nabice** [comment] 2017-11-15 05:07
@gbrail, I found it still not fixed. FunctionNode has wrong position.

**Comment by gbrail** [comment] 2017-11-15 17:15
OK. I must be misunderstanding the problem then. Perhaps if you can give us
some code to reproduce it and describe what's incorrect then we can take a
look.

**Comment by nabice** [comment] 2017-11-16 02:44
file: a.js
`setTimeout(() => {}, 0);`

When a.js is parsed, setTimeout's first argument is a FucntionNode instance. Property `position` of the instance should be 12, but 0 we get.
It can be fixed like this, probably not correct:

```
diff --git a/src/org/mozilla/javascript/Parser.java b/src/org/mozilla/javascript/Parser.java
index da03f0c7..787e8bc3 100644
--- a/src/org/mozilla/javascript/Parser.java
+++ b/src/org/mozilla/javascript/Parser.java
@@ -3106,7 +3106,7 @@ public class Parser
             Comment jsdocNode = getAndResetJsDoc();
             int lineno = ts.lineno;
             int begin = ts.tokenBeg;
-            AstNode e = (peekToken() == Token.RP ? new EmptyExpression() : expr());
+            AstNode e = (peekToken() == Token.RP ? new EmptyExpression(ts.tokenBeg) : expr());
             if (peekToken() == Token.FOR) {
                 return generatorExpression(e, begin);
             }
```

**Comment by sainaen** [comment] 2017-11-16 14:55
@nabice 
For what it's worth, I don't see how to fix this differently. I even went ahead and create a pull request. 🙂 

Well, there's one minor thing: I noticed that this way position will point at the opening parenthesis, while in case of parameters present (e.g. `(a, b) => a+b`) it will be one character further (`ParenthesisedExpression` copies its child position) — is it ok? (See the test in my PR for example of this.)

**Comment by gbrail** [comment] 2017-11-18 00:01
Can you please take a look at @sainaen 's PR and see if it fixes this for you?

https://github.com/mozilla/rhino/pull/363

Thanks!

**Comment by nabice** [comment] 2017-11-18 00:55
Yes, it does.

**Closed** 2017-11-18 01:15 UTC
