### ISSUE TITLE
Chinese users cannot view rhino documents properly

### ISSUE THREAD

**Issue by etjson** [mozilla/rhino#1197] opened 2022-03-24 06:14 UTC
![image](https://user-images.githubusercontent.com/41315967/159853713-d8705e21-723e-4f20-a9ad-f6b0f63d2e12.png)

Chinese users cannot view rhino documents properly.

**Comment by p-bakker** [comment] 2022-03-24 07:32
Duplicate of #954

Mozilla removed all the docs they aren't maintaining anymore, including the Rhino docs.

We're in the process of hosting the docs here in this repo, see #954

**Closed by p-bakker** 2022-03-24 07:32 UTC
