### ISSUE TITLE
Rhino 1.7.14 is not available under Android SDK 21

### ISSUE THREAD

**Issue by ylk2534246654** [mozilla/rhino#1156] opened 2022-01-12 17:53 UTC
Rhino 1.7.13 worked well before.
Stack trace:
`
java.lang.NoClassDefFoundError: org.mozilla.javascript.NativeError$$ExternalSyntheticLambda4
        at org.mozilla.javascript.NativeError.fillConstructorProperties(NativeError.java:82)
        at org.mozilla.javascript.IdScriptableObject.exportAsJSClass(IdScriptableObject.java:725)
        at org.mozilla.javascript.NativeError.init(NativeError.java:38)
        at org.mozilla.javascript.ScriptRuntime.initSafeStandardObjects(ScriptRuntime.java:162)
        at org.mozilla.javascript.ScriptRuntime.initStandardObjects(ScriptRuntime.java:300)
        at org.mozilla.javascript.Context.initStandardObjects(Context.java:1076)
        at org.mozilla.javascript.Context.initStandardObjects(Context.java:980)
`

**Comment by p-bakker** [comment] 2022-01-12 18:54
Duplicate of #1149

**Comment by p-bakker** [comment] 2022-01-12 18:56
Also see #1149

**Comment by p-bakker** [comment] 2023-11-02 18:18
As this supposedly is a duplicate of #1149, which has been resolved, I'm gonna close this issue as well

**Closed by p-bakker** 2023-11-02 18:18 UTC
Labels: Android, Regression
