### ISSUE TITLE
NoClassDefFoundError problem when using Rhino 1.7.14 in Android

### ISSUE THREAD

**Issue by snechiporenko** [mozilla/rhino#1155] opened 2022-01-10 12:09 UTC
Rhino 1.7.14 not find the javax.lang.model.SourceVersion class, because android not able to use javax namespace

>Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/lang/model/SourceVersion;
    at org.mozilla.javascript.JavaMembers.<clinit>(JavaMembers.java:37)
    at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:769)
    at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:50)
    at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:53)
    at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:44)
    at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:40)
    at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:136)
    at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:134)
    at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84)
    at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2023)
    at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1672)
    at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1667)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1551)

Another similar problem [https://github.com/mozilla/rhino/issues/560](url)

**Comment by p-bakker** [comment] 2022-01-10 13:07
Duplicate of #1149

**Closed by p-bakker** 2022-01-10 13:07 UTC
